### ISSUE TITLE
phosphor-dbus-monitor: the logging behavior would be abnormal if multi sensors are assigned.

### ISSUE THREAD

**Issue by henbin** [openbmc/openbmc#3356]
Hi,
I create a event-policy.yaml and  add a watch to monitor the CriticalAlarmLow of the voltage sensors.

The logging behavior would be abnormal if multi voltage sensors were assigned as the below,
```
- name: Critical Low sensors
  description: >
    'The sensors have critical low.'
  class: group
  group: path
  members:
    - meta: SENSOR
      path: /xyz/openbmc_project/sensors/voltage/P5V_AUX
    - meta: SENSOR
      path: /xyz/openbmc_project/sensors/voltage/P3V_BAT
```
I took P3V_BAT sensor for instance, 
1. Clear all logging entries.

2. gpioutil -n G4 --setval 0 to disable the input of battery voltage
"/xyz/openbmc_project/logging/entry/68" -> **P3V_BAT:CriticalAlarmLow=1**
"/xyz/openbmc_project/logging/entry/69" -> **P5V_AUX:CriticalAlarmLow=0**

3. gpioutil -n G4 --setval 1 to enable the input of battery voltage
-> no new logging entry be generated

4. gpioutil -n G4 --setval 0 to disable the input of battery voltage
"/xyz/openbmc_project/logging/entry/71" -> **P5V_AUX:CriticalAlarmLow=0**
"/xyz/openbmc_project/logging/entry/70" -> **P3V_BAT:CriticalAlarmLow=1**

The logging behavior would be correct as expected if only P3V_BAT sensor was assigned.
```
- name: Critical Low sensors
  description: >
    'The sensors have critical low.'
  class: group
  group: path
  members:
    - meta: SENSOR
      path: /xyz/openbmc_project/sensors/voltage/P3V_BAT
```
Could anyone provide the suggestion?

Attache the event-policy.yaml for reference.
[event-policy.zip](https://github.com/openbmc/openbmc/files/2277021/event-policy.zip)

Thanks.
