### ISSUE TITLE
Some problems in IPMI adding fan sensor

### ISSUE THREAD

**Issue by z1908144712** [openbmc/openbmc#3633]
My OpenBMC version is 2.7
```
root@xxxx:~# cat /etc/os-release 
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.7.0-0"
VERSION_ID="2.7.0-0-gcb91a7773-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.7.0-0"
BUILD_ID="2.7.0"
OPENBMC_TARGET_MACHINE="xxxx"
```
My YAML file:
```
1:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/temperature/cpu
    rExp: 0
    readingType: readingData
    scale: -3
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
2:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 100
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/fan_tach/fan1
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 4
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
3:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 100
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/fan_tach/fan2
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 4
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
4:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 100
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/fan_tach/fan3
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 4
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
5:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 100
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/fan_tach/fan4
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 4
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
6:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 100
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/fan_tach/fan5
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 4
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
7:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 100
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/fan_tach/fan6
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 4
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
8:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 100
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/fan_tach/fan7
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 4
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
9:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 100
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/fan_tach/fan8
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 4
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
10:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 5
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/voltage/CPUVCC09
    rExp: -3
    readingType: readingData
    scale: -3
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
11:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 11
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/voltage/VDD25
    rExp: -3
    readingType: readingData
    scale: -3
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
12:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 15
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/voltage/VSB33
    rExp: -3
    readingType: readingData
    scale: -3
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
13:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 5
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/voltage/8748_VDD09
    rExp: -3
    readingType: readingData
    scale: -3
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
14:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 5
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/voltage/ICH_VDD09
    rExp: -3
    readingType: readingData
    scale: -3
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
15:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 22
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/voltage/VDD5
    rExp: -3
    readingType: readingData
    scale: -3
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
16:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 8
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/voltage/VDD18
    rExp: -3
    readingType: readingData
    scale: -3
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
17:
    bExp: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 52
    offsetB: 0
    mutability: Mutability::Write|Mutability::Read
    path: /xyz/openbmc_project/sensors/voltage/12V_HCP0805_R
    rExp: -3
    readingType: readingData
    scale: -3
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
```
When I add some sensor to the IPMI, like temperature sensor, voltage sensor and fan sensor, threre are some problem here. I have  added them successfully, but only temperature and voltgae are normal, fan is not working properly. I don't know if this is a bug or if there is a problem with my configuration.
There are some test results:
```
ipmitool> sdr
fan1             | 2300 RPM          | ok
fan2             | no reading        | ns
fan3             | no reading        | ns
fan4             | no reading        | ns
fan5             | no reading        | ns
fan6             | no reading        | ns
fan7             | no reading        | ns
fan8             | no reading        | ns
CPUVCC09         | 1.06 Volts        | ok
VDD25            | 2.55 Volts        | ok
VSB33            | 3.42 Volts        | ok
8748_VDD09       | 0.96 Volts        | ok
ICH_VDD09        | 0.98 Volts        | ok
VDD5             | 5.15 Volts        | ok
VDD18            | 1.80 Volts        | ok
12V_HCP0805_R    | 12.17 Volts       | ok
```
```
ipmitool> sensor
fan1             | na         |            | na    | na        | 0.000     | 0.000     | 10100.000 | 10100.000 | na        
Get SDR 0002 command failed
fan2             | 1500.000   | RPM        | ok    | na        | 0.000     | 0.000     | 10100.000 | 10100.000 | na        
Get SDR 0003 command failed
fan3             | 1500.000   | RPM        | ok    | na        | 0.000     | 0.000     | 10100.000 | 10100.000 | na        
Get SDR 0004 command failed
fan4             | 0.000      | RPM        | ok    | na        | 0.000     | 0.000     | 10100.000 | 10100.000 | na        
Get SDR 0005 command failed
fan5             | 0.000      | RPM        | ok    | na        | 0.000     | 0.000     | 10100.000 | 10100.000 | na        
Get SDR 0006 command failed
fan6             | 0.000      | RPM        | ok    | na        | 0.000     | 0.000     | 10100.000 | 10100.000 | na        
Get SDR 0007 command failed
fan7             | 0.000      | RPM        | ok    | na        | 0.000     | 0.000     | 10100.000 | 10100.000 | na        
Get SDR 0008 command failed
fan8             | 3700.000   | RPM        | ok    | na        | 0.000     | 0.000     | 10100.000 | 10100.000 | na        
Get SDR 0009 command failed
CPUVCC09         | 1.065      | Volts      | ok    | na        | 0.810     | 0.810     | 1.125     | 1.125     | na        
VDD25            | 2.552      | Volts      | ok    | na        | 2.288     | 2.288     | 2.750     | 2.750     | na        
VSB33            | 3.420      | Volts      | ok    | na        | 3.030     | 3.030     | 3.645     | 3.645     | na        
8748_VDD09       | 0.960      | Volts      | ok    | na        | 0.810     | 0.810     | 1.125     | 1.125     | na        
ICH_VDD09        | 0.985      | Volts      | ok    | na        | 0.810     | 0.810     | 1.125     | 1.125     | na        
VDD5             | 5.148      | Volts      | ok    | na        | 4.620     | 4.620     | 5.566     | 5.566     | na        
VDD18            | 1.800      | Volts      | ok    | na        | 1.664     | 1.664     | 1.992     | 1.992     | na        
12V_HCP0805_R    | 12.116     | Volts      | ok    | na        | 11.024    | 11.024    | 13.260    | 13.260    | na 
```
Actually fan1-3 and fan8 are normal, others are not used. Can someone give me some advice ?
