### ISSUE TITLE
Can't  list FRUs via ipmitool

### ISSUE THREAD

**Issue by wu790607** [openbmc/openbmc#3785]
Hi all

I am new to openBMC, I build the own system and want to get FRU list via ipmitool command.
But I get the error message below as
```
root@nsdbmc:~# ipmitool fru 
FRU Device Description : Builtin FRU Device (ID 0)
FRU Device Description : cpu0 (ID 1)
 Device not present (Requested sensor, data, or record not found)

FRU Device Description : cpu1 (ID 2)
 Device not present (Requested sensor, data, or record not found)

FRU Device Description : system (ID 3)
 Device not present (Requested sensor, data, or record not found)

FRU Device Description : dimm0 (ID 4)
 Device not present (Requested sensor, data, or record not found)

FRU Device Description : dimm1 (ID 5)
 Device not present (Requested sensor, data, or record not found)

FRU Device Description : dimm2 (ID 6)
 Device not present (Requested sensor, data, or record not found)

FRU Device Description : dimm3 (ID 7)
 Device not present (Requested sensor, data, or record not found)


```

I add the yaml file 
```
0:
  /system/chassis/bmc:
    entityID: 6
    entityInstance: 1
    interfaces:
      xyz.openbmc_project.Inventory.Decorator.Asset:
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Board
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Board
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Board
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Board
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Board
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: FRU File ID
          IPMIFruSection: Board

1:
    /system/chassis/motherboard/cpu0:
        entityID: 3
        entityInstance: 1
        interfaces:
            xyz.openbmc_project.Inventory.Decorator.Asset:
                BuildDate:
                    IPMIFruProperty: Mfg Date
                    IPMIFruSection: Board
                Manufacturer:
                    IPMIFruProperty: Manufacturer
                    IPMIFruSection: Board
                PartNumber:
                    IPMIFruProperty: Part Number
                    IPMIFruSection: Board
                SerialNumber:
                    IPMIFruProperty: Serial Number
                    IPMIFruSection: Board
            xyz.openbmc_project.Inventory.Decorator.Revision:
                Version:
                    IPMIFruProperty: Custom Field 2
                    IPMIFruSection: Board
                    IPMIFruValueDelimiter: 58
            xyz.openbmc_project.Inventory.Item:
                PrettyName:
                    IPMIFruProperty: Name
                    IPMIFruSection: Board
2:
    /system/chassis/motherboard/cpu1:
        entityID: 3
        entityInstance: 2
        interfaces:
            xyz.openbmc_project.Inventory.Decorator.Asset:
                BuildDate:
                    IPMIFruProperty: Mfg Date
                    IPMIFruSection: Board
                Manufacturer:
                    IPMIFruProperty: Manufacturer
                    IPMIFruSection: Board
                PartNumber:
                    IPMIFruProperty: Part Number
                    IPMIFruSection: Board
                SerialNumber:
                    IPMIFruProperty: Serial Number
                    IPMIFruSection: Board
            xyz.openbmc_project.Inventory.Decorator.Revision:
                Version:
                    IPMIFruProperty: Custom Field 2
                    IPMIFruSection: Board
                    IPMIFruValueDelimiter: 58
            xyz.openbmc_project.Inventory.Item:
                PrettyName:
                    IPMIFruProperty: Name
                    IPMIFruSection: Board
                    Value: false
3:
    /system:
        entityID: 7
        entityInstance: 1
        interfaces:
            xyz.openbmc_project.Inventory.Decorator.Asset:
                Model:
                    IPMIFruProperty: Part Number
                    IPMIFruSection: Chassis
                SerialNumber:
                    IPMIFruProperty: Serial Number
                    IPMIFruSection: Chassis
    /system/chassis/motherboard:
        entityID: 7
        entityInstance: 1
        interfaces:
            xyz.openbmc_project.Inventory.Decorator.Asset:
                BuildDate:
                    IPMIFruProperty: Mfg Date
                    IPMIFruSection: Board
                Manufacturer:
                    IPMIFruProperty: Manufacturer
                    IPMIFruSection: Board
                PartNumber:
                    IPMIFruProperty: Part Number
                    IPMIFruSection: Board
                SerialNumber:
                    IPMIFruProperty: Serial Number
                    IPMIFruSection: Board
            xyz.openbmc_project.Inventory.Item:
                PrettyName:
                    IPMIFruProperty: Name
                    IPMIFruSection: Board
4:
    /system/chassis/motherboard/dimm0:
        entityID: 32
        entityInstance: 1
        interfaces:
            xyz.openbmc_project.Inventory.Decorator.Asset:
                BuildDate:
                    IPMIFruProperty: Mfg Date
                    IPMIFruSection: Product
                Manufacturer:
                    IPMIFruProperty: Manufacturer
                    IPMIFruSection: Product
                Model:
                    IPMIFruProperty: Model Number
                    IPMIFruSection: Product
                PartNumber:
                    IPMIFruProperty: Part Number
                    IPMIFruSection: Product
                SerialNumber:
                    IPMIFruProperty: Serial Number
                    IPMIFruSection: Product
            xyz.openbmc_project.Inventory.Decorator.Revision:
                Version:
                    IPMIFruProperty: Version
            xyz.openbmc_project.Inventory.Item:
                PrettyName:
                    IPMIFruProperty: Name
                    IPMIFruSection: Product
5:
    /system/chassis/motherboard/dimm1:
        entityID: 32
        entityInstance: 2
        interfaces:
            xyz.openbmc_project.Inventory.Decorator.Asset:
                BuildDate:
                    IPMIFruProperty: Mfg Date
                    IPMIFruSection: Product
                Manufacturer:
                    IPMIFruProperty: Manufacturer
                    IPMIFruSection: Product
                Model:
                    IPMIFruProperty: Model Number
                    IPMIFruSection: Product
                PartNumber:
                    IPMIFruProperty: Part Number
                    IPMIFruSection: Product
                SerialNumber:
                    IPMIFruProperty: Serial Number
                    IPMIFruSection: Product
            xyz.openbmc_project.Inventory.Decorator.Revision:
                Version:
                    IPMIFruProperty: Version
            xyz.openbmc_project.Inventory.Item:
                PrettyName:
                    IPMIFruProperty: Name
                    IPMIFruSection: Product
6:
    /system/chassis/motherboard/dimm2:
        entityID: 32
        entityInstance: 3
        interfaces:
            xyz.openbmc_project.Inventory.Decorator.Asset:
                BuildDate:
                    IPMIFruProperty: Mfg Date
                    IPMIFruSection: Product
                Manufacturer:
                    IPMIFruProperty: Manufacturer
                    IPMIFruSection: Product
                Model:
                    IPMIFruProperty: Model Number
                    IPMIFruSection: Product
                PartNumber:
                    IPMIFruProperty: Part Number
                    IPMIFruSection: Product
                SerialNumber:
                    IPMIFruProperty: Serial Number
                    IPMIFruSection: Product
            xyz.openbmc_project.Inventory.Decorator.Revision:
                Version:
                    IPMIFruProperty: Version
            xyz.openbmc_project.Inventory.Item:
                PrettyName:
                    IPMIFruProperty: Name
                    IPMIFruSection: Product
7:
    /system/chassis/motherboard/dimm3:
        entityID: 32
        entityInstance: 4
        interfaces:
            xyz.openbmc_project.Inventory.Decorator.Asset:
                BuildDate:
                    IPMIFruProperty: Mfg Date
                    IPMIFruSection: Product
                Manufacturer:
                    IPMIFruProperty: Manufacturer
                    IPMIFruSection: Product
                Model:
                    IPMIFruProperty: Model Number
                    IPMIFruSection: Product
                PartNumber:
                    IPMIFruProperty: Part Number
                    IPMIFruSection: Product
                SerialNumber:
                    IPMIFruProperty: Serial Number
                    IPMIFruSection: Product
            xyz.openbmc_project.Inventory.Decorator.Revision:
                Version:
                    IPMIFruProperty: Version
            xyz.openbmc_project.Inventory.Item:
                PrettyName:
                    IPMIFruProperty: Name
                    IPMIFruSection: Product

```

```
/system:
    xyz.openbmc_project.Inventory.Decorator.Cacheable:
        Cached: 'true'
    xyz.openbmc_project.Inventory.Decorator.Replaceable:
        FieldReplaceable: 'true'
    xyz.openbmc_project.Inventory.Item:
        Present: 'true'
/system/chassis/motherboard:
    xyz.openbmc_project.Inventory.Decorator.Cacheable:
        Cached: 'true'
    xyz.openbmc_project.Inventory.Decorator.Replaceable:
        FieldReplaceable: 'true'
    xyz.openbmc_project.Inventory.Item:
        Present: 'true'
/system/chassis/motherboard/cpu0:
    xyz.openbmc_project.Inventory.Decorator.Cacheable:
        Cached: 'true'
    xyz.openbmc_project.Inventory.Decorator.Replaceable:
        FieldReplaceable: 'true'
    xyz.openbmc_project.Inventory.Item:
        Present: 'true'
/system/chassis/motherboard/cpu1:
    xyz.openbmc_project.Inventory.Decorator.Cacheable:
        Cached: 'true'
    xyz.openbmc_project.Inventory.Decorator.Replaceable:
        FieldReplaceable: 'true'
    xyz.openbmc_project.Inventory.Item:
        Present: 'true'
/system/chassis/motherboard/dimm0:
    xyz.openbmc_project.Inventory.Decorator.Cacheable:
        Cached: 'true'
    xyz.openbmc_project.Inventory.Decorator.Replaceable:
        FieldReplaceable: 'true'
    xyz.openbmc_project.Inventory.Item:
        Present: 'true'
/system/chassis/motherboard/dimm1:
    xyz.openbmc_project.Inventory.Decorator.Cacheable:
        Cached: 'true'
    xyz.openbmc_project.Inventory.Decorator.Replaceable:
        FieldReplaceable: 'true'
    xyz.openbmc_project.Inventory.Item:
        Present: 'true'
/system/chassis/motherboard/dimm2:
    xyz.openbmc_project.Inventory.Decorator.Cacheable:
        Cached: 'true'
    xyz.openbmc_project.Inventory.Decorator.Replaceable:
        FieldReplaceable: 'true'
    xyz.openbmc_project.Inventory.Item:
        Present: 'true'
/system/chassis/motherboard/dimm3:
    xyz.openbmc_project.Inventory.Decorator.Cacheable:
        Cached: 'true'
    xyz.openbmc_project.Inventory.Decorator.Replaceable:
        FieldReplaceable: 'true'
    xyz.openbmc_project.Inventory.Item:
        Present: 'true'
```

Am I missing something? 
Please kindly tell me the solution.

Many thanks
