### ISSUE TITLE
FRU Device service did not start

### ISSUE THREAD

**Issue by damon3000** [openbmc/openbmc#3837]
**Note on Bugs**
1. I created a layer based on meta-romulus
2. Modify the aspeed-bmc-opp-romulus.dts to configure eeprom
```
&i2c3 {
        status = "okay";
        eeprom@50 {
                compatible = "atmel,24c64";
                reg = <0x50>;
        };
};

```
3. Modify the yaml file to add my fru configuration
```
1:
    /xyz/openbmc_project/FruDevice/XX0123456789ABEVT001:
        entityID: 3
        entityInstance: 1
        interfaces:
            xyz.openbmc_project.Inventory.Decorator.Asset:
                BuildDate:
                    IPMIFruProperty: Mfg Date
                    IPMIFruSection: Board
                Manufacturer:
                    IPMIFruProperty: Manufacturer
                    IPMIFruSection: Board
                PartNumber:
                    IPMIFruProperty: Part Number
                    IPMIFruSection: Board
                SerialNumber:
                    IPMIFruProperty: Serial Number
                    IPMIFruSection: Board
            xyz.openbmc_project.Inventory.Decorator.Revision:
                Version:
                    IPMIFruProperty: Custom Field 2
                    IPMIFruSection: Board
                    IPMIFruValueDelimiter: 58
            xyz.openbmc_project.Inventory.Item:
                PrettyName:
                    IPMIFruProperty: Name
                    IPMIFruSection: Board

```
4. Boot up BMC 

**Unexpected behavior you saw**
FRU Device service did not start
```
root@sky:/etc/systemd/system/multi-user.target.wants# systemctl status nbmc_project.FruDevice.service
* xyz.openbmc_project.FruDevice.service - Fru Device
     Loaded: loaded (/lib/systemd/system/xyz.openbmc_project.FruDevice.service; disabled; vendor preset: disabled)
     Active: inactive (dead)
root@sky:
```
Checked the preset file after compiled, but found that the service is disabled default:
```
work/sky-openbmc-linux-gnueabi/obmc-phosphor-image/1.0-r0/rootfs/lib/systemd/system-preset/98-fru-device.preset:1:disable xyz.openbmc_project.FruDevice.service
```

**Expected behavior**
FRU Device service can start normal.

**OpenBMC Information:**
```
root@sky:/etc/systemd/system/multi-user.target.wants# cat /etc/os-release 
ID=openbmc-romulus
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.9.0-0"
VERSION_ID=2.9.0-0-g835472cca-dirty
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.9.0-0"
BUILD_ID="2.9.0"
OPENBMC_TARGET_MACHINE="sky"
root@sky:/etc/systemd/system/multi-user.target.wants# uname -a
Linux sky 5.8.17 #1 Mon Dec 6 09:41:35 UTC 2021 armv6l GNU/Linux
root@sky:/etc/systemd/system/multi-user.target.wants#
```
